In [ ]:
#Create a class function using one of the magic functions but you cannot use __mul__ 
#Create a class function that the child class inherit from parent class
#Create a 2-D array and transform it to transponse matrix
# _sub_for -
# _mul__ for *
# _truediv__for /
# _floordiv_for //
# _mod_for %
# _pow_for**
# _and_for &
# _xor_for ^
# _or_for

# _it_ for <
# _le_ for <=
# _eq_for ==
# _ne_for !=
# _gt_for >
# _ge_ for>=

In [20]:
class Employee:
    def __init__(self, name, salary):
        self.name= name
        self.salary=salary
    def __str__(self):
        return 'Employee Name: '+ self.name +' , Employee salary:  $'+str(self.salary)

Manager=Employee('Oluk Isaac', 40000)
Manager2=Employee('Nabwire Shona', 80000)

print(Manager)
print(Manager2)

Employee Name: Oluk Isaac , Employee salary:  $40000
Employee Name: Nabwire Shona , Employee salary:  $80000


In [22]:
class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname

  def printname(self):
    print(self.firstname, self.lastname)

# class Student(Person):
#   pass

# x = Student("Mike", "Olsen")
# x.printname()

class Student(Person):
  def __init__(self, fname, lname, year):
    super().__init__(fname, lname)
    self.graduationyear = year

  def welcome(self):
    print("Welcome", self.firstname, self.lastname, "to the class of", self.graduationyear)

x = Student("Mike", "Olsen", 2019)
x.welcome()

Welcome Mike Olsen to the class of 2019


In [23]:
import numpy
l1= [[4, 5, 3, 9], [7, 1, 8, 2], [5, 6, 4, 7]]
print(numpy.transpose(l1))

[[4 7 5]
 [5 1 6]
 [3 8 4]
 [9 2 7]]


In [6]:
class find_vector:
    def __init__(self, number1,number2):
        self.number1 = number1
        self.number2 = number2

    def __add__(self, addition):
        return find_vector(self.number1 + addition.number1, self.number2 + addition.number2)

first_position = find_vector(20,100)
second_position = find_vector(30,50)

combine = first_position + second_position

print(combine.number1)
print(combine.number2)

50
150


In [17]:
#Class Quiz runthrough

class family_tree:
    def __init__(self,dad,mom,son):
        self.dad = dad
        self.mom = mom
        self.son = son

class son_hobbies(family_tree):
    def hobbies(self):
        print(self.son + '\'s Hobbies are Basketball, Swimming and Math' )

tree = family_tree('Jefferey', 'Sheba', 'Jonathan')
son_tree = son_hobbies('Jeffrey','Sheba', 'Jonathan')

print(tree.dad , tree.mom , tree.son)
print(son_tree.son)

son_tree.hobbies()

Jefferey Sheba Jonathan
Jonathan
Jonathan's Hobbies are Basketball, Swimming and Math
