In [12]:
# Create a tuple with a list of items and convert that tuple into a list.

names = ('Brenda', 'Grace', 'Hannah', 'Mckinsey')
print(names)

namesList = list(names)
print(namesList)

# Add 2 more items and then convert it back to a tuple.
namesList.extend(['Nakato', 'Jasmine'])
print(namesList)

namesListTuple = tuple(namesList)
print(namesListTuple)


('Brenda', 'Grace', 'Hannah', 'Mckinsey')
['Brenda', 'Grace', 'Hannah', 'Mckinsey']
['Brenda', 'Grace', 'Hannah', 'Mckinsey', 'Nakato', 'Jasmine']
('Brenda', 'Grace', 'Hannah', 'Mckinsey', 'Nakato', 'Jasmine')


In [15]:
#Create a 3-D Numpy Array 
import numpy as np
arrThreeD = np.array([[3,4,5,6,7], [10,20,30,40,50],[30,35,36,37,38]])
print(arrThreeD)



[[ 3  4  5  6  7]
 [10 20 30 40 50]
 [30 35 36 37 38]]


In [28]:
#Create a function that prints odd numbers
def odds(max):
    oddList=[]
    for i in range(max):
        if i % 2 !=0:
            oddList.append(i)
    print(oddList)

odds(20)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [ ]:
# create a tuple with a list of items and convert it to a list
def create_tuple(length):
    t = ()
    for i in range(length):
        t += (i,)
    return list(t)

# Add two more items the list and then convert it back to a tuple
def add_two_items(t):
    t += [2, 3]
    return tuple(t)

# create a 3-D numpy array
def create_3d_array(n):
    # return a 3-D array with n for 3 rows and 3 columns
    return np.array([[[i, i, i] for i in range(n)]])

# create a function that print odd numbers using numpy
def print_odd_numbers(n):
    for i in range(n):
        if i % 2 != 0:
            print(i)


if __name__ == '__main__':
    print(create_tuple(5))

    tp = create_tuple(5)
    print(add_two_items(tp))

    print(create_3d_array(3))

    print_odd_numbers(15)