In [6]:
print(' I have {} dollars and I\'m still {} broke'.format(20, 'broke'))

weekDays = ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday')

report = 'Days of the week: {0} \nFirstDay: {1}'.format(
    weekDays[0], weekDays[1])

print(report)


 I have 20 dollars and I'm still broke broke
Days of the week: Monday 
FirstDay: Tuesday


In [14]:
import numpy as np

time1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
time = np.array([1, 2, 3, 4, 5,6, 7, 8, 9, 10])
interval = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

#Ravel flattens the array; makes a 2 dimensional array into a one dimensional array
print(time1.ravel()) 

print(np.multiply(time, interval))
print(np.add(time, interval))
# How many numbers are greater than 50 in the arrays
print((time > 50).sum())
print((interval > 50).sum())


[ 1  2  3  4  5  6  7  8  9 10]
[  10   40   90  160  250  360  490  640  810 1000]
[ 11  22  33  44  55  66  77  88  99 110]
0
5
