In [1]:
#tuples
tup = ('Math', 'Science', 'Reading', 'Chemistry', 'history')

print(tup[1])

print(tup[:1])

for i in tup:
    print (i)
    

Science
('Math',)
Math
Science
Reading
Chemistry
history


In [2]:
import numpy as np

arr = np.array([[1,2,3,4,5,6,7,], [8,9,10,11,12,13,14]]) 

print(arr)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
#Matrix Transpose
arr1 = np.array([[10,12,13,14,15,16],[30,31,32,33,34,35],[56,55,54,57,98,35]])

print(arr1)

print(arr1.transpose())

[[10 12 13 14 15 16]
 [30 31 32 33 34 35]
 [56 55 54 57 98 35]]
[[10 30 56]
 [12 31 55]
 [13 32 54]
 [14 33 57]
 [15 34 98]
 [16 35 35]]
